### ISSUE TITLE
Error with installer: "cannot open shared object file"

### ISSUE THREAD

**Issue by Ao1Pointblank** [Sound-Linux-More/libopustags#1]
opustags works when run from it's home folder, but after ``sudo make install``, it has a pretty major error which prevents it from even displaying --help:

opustags: error while loading shared libraries: libopustags.so.1: cannot open shared object file: No such file or directory

Running on Linux Mint Cinnamon 21.2
While I'm here, let me ask you to consider making it installable without sudo?

**Comment by zvezdochiot** [comment]
@Ao1Pointblank , you have problems installing shared libraries: libopustags.so.1. Copy it manually to your library directory.

Recommends: https://github.com/Sound-Linux-More/opuscomment
